indicators:
  - key: "mvc-child-headed-M-17"
    grouping: "MVC"
    description: "Number of Households Headed by Male Children aged 17 and below"
    indicatorQuery: " SELECT count(DISTINCT eor.base_entity_id) as count
                      FROM ec_ovc_register eor
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = eor.base_entity_id
                      WHERE  (date('Now') - date(efm.dob))  <=17
                      AND head_of_household = 'child'
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 7) || '-' || '01')) =
                          date(substr(strftime('%Y-%m-%d', datetime(eor.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 7) || '-' || '01')"
    
  - key: "mvc-child-headed-F-17"
    grouping: "MVC"
    description: "Number of Households Headed by Fema Children aged 17 and below"
    indicatorQuery: " SELECT count(DISTINCT eor.base_entity_id) as count
                      FROM ec_ovc_register eor
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = eor.base_entity_id
                      WHERE  (date('Now') - date(efm.dob))  <=17
                      AND head_of_household = 'child'
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 7) || '-' || '01')) =
                          date(substr(strftime('%Y-%m-%d', datetime(eor.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 7) || '-' || '01')"
    
  - key: "mvc-adult-headed-M-17"
    grouping: "MVC"
    description: "Number of Households Headed by Male Adult aged 17 and below"
    indicatorQuery: " SELECT count(DISTINCT eor.base_entity_id) as count
                      FROM ec_ovc_register eor
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = eor.base_entity_id
                      WHERE  (date('Now') - date(efm.dob))  <=17
                      AND head_of_household = 'adult'
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 7) || '-' || '01')) =
                          date(substr(strftime('%Y-%m-%d', datetime(eor.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 7) || '-' || '01')"
    
  - key: "mvc-adult-headed-F-17"
    grouping: "MVC"
    description: "Number of Households Headed by Fema Adult aged 17 and below"
    indicatorQuery: " SELECT count(DISTINCT eor.base_entity_id) as count
                      FROM ec_ovc_register eor
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = eor.base_entity_id
                      WHERE  (date('Now') - date(efm.dob))  <=17
                      AND head_of_household = 'adult'
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 7) || '-' || '01')) =
                          date(substr(strftime('%Y-%m-%d', datetime(eor.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 7) || '-' || '01')"
    
  - key: "mvc-elderly-headed-M-17"
    grouping: "MVC"
    description: "Number of Households Headed by Male Adult aged 17 and below"
    indicatorQuery: " SELECT count(DISTINCT eor.base_entity_id) as count
                      FROM ec_ovc_register eor
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = eor.base_entity_id
                      WHERE  (date('Now') - date(efm.dob))  <=17
                      AND head_of_household = 'elderly'
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 7) || '-' || '01')) =
                          date(substr(strftime('%Y-%m-%d', datetime(eor.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 7) || '-' || '01')"
    
  - key: "mvc-elderly-headed-F-17"
    grouping: "MVC"
    description: "Number of Households Headed by Fema Adult aged 17 and below"
    indicatorQuery: " SELECT count(DISTINCT eor.base_entity_id) as count
                      FROM ec_ovc_register eor
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = eor.base_entity_id
                      WHERE  (date('Now') - date(efm.dob))  <=17
                      AND head_of_household = 'elderly'
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 7) || '-' || '01')) =
                          date(substr(strftime('%Y-%m-%d', datetime(eor.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 7) || '-' || '01')"