indicators:
  #Question 1
  #Male
  - key: "sbc-1-male-10-14"
    grouping: "MVC"
    description: "Number of Male individuals from 10-14 years old who were reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT esr.base_entity_id) as count
                      FROM ec_sbc_register esr
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = esr.base_entity_id
                      WHERE 10 <= (date('Now') - date(efm.dob))  AND (date('Now')-date(efm.dob))<=14
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(esr.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(esr.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-male-15-19"
    grouping: "MVC"
    description: "Number of Male individuals from 15-19 years old who were reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT esr.base_entity_id) as count
                      FROM ec_sbc_register esr
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = esr.base_entity_id
                      WHERE 15 <= (date('Now') - date(efm.dob))  AND (date('Now')-date(efm.dob))<=19
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(esr.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(esr.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

